name: rssh with public key oe ec2
on: 
   workflow_dispatch:
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: 13.127.188.175
        username: ec2-user
        key: ${{ secrets.PUBLICKEYAWS }}
        port: 22
        script: whoami

