
name: remote ssh command
on: 
   workflow_dispatch:
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 3.111.186.51
        username: ubuntu
        password: Sandy#0707
        port: 22
        script: whoami
