
name: remote ssh command
on: 
   workflow_dispatch:
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: 13.127.188.175
        username: ec2-user
        key: ${{ secrets.PRIVATEKEY }}
        port: 22
        script: whoami
    - name: Send mail
      if: always()
      uses: dawidd6/action-send-mail@v2
      with:
          # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
                 # user credentials
        username: er.patilmangesh@gmail.com
        password: 9561356157
               # email subject
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
                  # email body as text
        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
                  # comma-separated string, send email to
        to: sandiplondhe3@gmail.com
                # from email name
        from: Mangesh Patil
        

     
                
